---
abstract: 'A simple command-line shell framework.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Test: 0
  Test::More: 0
  vars: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
keywords:
  - console
  - readline
  - shell
  - term
  - terminal
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Shell
provides:
  Term::Shell:
    file: lib/Term/Shell.pm
    version: 0.02
  Term::Shell::OnScopeLeave:
    file: lib/Term/Shell.pm
    version: 0
requires:
  Data::Dumper: 0
  Term::ReadLine: 0
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/shlomif/Term-Shell
version: 0.02
